[tool.poetry]
name = "neetcode"
version = "0.1.0"
description = ""
authors = ["Dmytro Soltysiuk <dimasoltusyuk@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
pytest = "^7.3.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
